### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by Tooneytunes** [mbreemhaar/thiliumbot#4]
**Is your feature request related to a problem? Please describe.**
We hebben een timer nodig voor als we bijvoorbeeld met veel mensen battle royale doen, dan kunnen we teams scramblen na een bepaalde tijd

**Describe the solution you'd like**
$timer 60 (in minuten)

**Additional context**
Na een bepaalde tijd verstreken bijvoorbeeld 50 & 75% zegt hij iets met /tts in discord voor hoeveel tijd er nog over is

**Comment by mbreemhaar** [comment]
Text to speech is not a good way of doing reminders, because every member of the Discord server will hear it. I could do it as a simple text message, although it's much easier to miss that. Another way would be to get the bot in a voice channel when sending a reminder to call it out there, but I haven't figured out how to do stuff like that yet.

**Comment by mbreemhaar** [comment]
I implemented it without tts for now
