### ISSUE TITLE
DJ BOT

### ISSUE THREAD

**Issue by Tooneytunes** [mbreemhaar/thiliumbot#6]
**Is your feature request related to a problem? Please describe.**
Het is wel een probleem als we muziek op moeten zetten en als we iemand moeten aanwijzen als de designated DJ. Dan komt het er vaak op neer dat we één van die godvergeten kutplaylists van Toon opzetten die we allemaal te vaak al hebben gehoord. 

**Describe the solution you'd like**
$DJ add <youtube/soundcloud/spotify link>
Hij speelt een random nummer af uit de afspeellijst van alle afgespeelde nummers

**Additional context**
$DJ voteskip < Als de helft van de mensen in de lobby deze command doen dan wordt het nummer geskipt

**Comment by mbreemhaar** [comment]
Well, that's probably going to take a while to implement. We currently have Rhythm in the server, which works well I think.

A simple way to solve your problem would be to have Thilium Bot be the only one with DJ rights in the server. Thilium Bot could then pass on commands to Rhythm in any way you would like it to be implemented. This way, you would be able to tell Thilium Bot to add something to the playlist, but not skip it because more than half of the voice chat will have to agree first.

However, since this is quite complicated to do the way Thilium Bot's code is structured right now, I'll leave this feature for later. Maybe just turn on your own playlist and mute Rhythm for now? :)
